Narrow down failure #2

diff --git a/pipelines/setup_clang.yml b/pipelines/setup_clang.yml
--- a/pipelines/setup_clang.yml
+++ b/pipelines/setup_clang.yml
@@ -9,9 +9,9 @@ steps:
       if [ "${{ parameters.version }}" = "13" ]
       then # see https://apt.llvm.org/
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
-        echo "UPDATING"
-        (sudo apt-get update) 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
+        # sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
+        # echo "UPDATING"
+        # (sudo apt-get update) 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
         # echo "INSTALLING CLANG"
         # (sudo apt-get install clang-13) 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
         # wget https://apt.llvm.org/llvm.sh
