Log errors

diff --git a/pipelines/setup_clang.yml b/pipelines/setup_clang.yml
--- a/pipelines/setup_clang.yml
+++ b/pipelines/setup_clang.yml
@@ -10,8 +10,10 @@ steps:
       then # see https://apt.llvm.org/
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
         sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
-        sudo apt-get update
-        sudo apt-get install clang-13
+        echo "UPDATING"
+        (sudo apt-get update) 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
+        echo "INSTALLING CLANG"
+        (sudo apt-get install clang-13) 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
         # wget https://apt.llvm.org/llvm.sh
         # chmod +x llvm.sh
         # sudo ./llvm.sh 13
